#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

WINE="${WINE:-wine}"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/blue-wine-smoke.XXXXXX")"
cleanup() { rm -rf "$TMP_ROOT"; }
trap cleanup EXIT

echo "=== build Windows compiler ==="
make windows

echo "=== wine: version/help ==="
"$WINE" blue_bin.exe --version | grep -q '^blue '
"$WINE" blue_bin.exe --help 2>&1 | grep -q 'JavaScript-to-native compiler'

echo "=== wine: parse and emit C++ ==="
"$WINE" blue_bin.exe --print-c examples/aot-math/main.js > "$TMP_ROOT/aot_math.cc"
grep -q 'Generated by Blue' "$TMP_ROOT/aot_math.cc"
grep -q 'js_console_log' "$TMP_ROOT/aot_math.cc"

echo "=== wine: init scaffold ==="
"$WINE" blue_bin.exe -init "$TMP_ROOT/init-app"
test -f "$TMP_ROOT/init-app/src/main.js"
test -f "$TMP_ROOT/init-app/src/island.js"
test -f "$TMP_ROOT/init-app/blue.config.json"
grep -q '"hybrid": true' "$TMP_ROOT/init-app/blue.config.json"

echo "=== wine: nested Windows compile ==="
if "$WINE" cmd /c g++ --version >/dev/null 2>&1; then
  "$WINE" blue_bin.exe -compile examples/aot-math/main.js -o "$TMP_ROOT/blue_math_win.exe"
  "$WINE" "$TMP_ROOT/blue_math_win.exe" | tr -d '\r' > "$TMP_ROOT/blue_math_win.out"
  grep -Fxq '5999995' "$TMP_ROOT/blue_math_win.out"
  grep -Fxq '50005000' "$TMP_ROOT/blue_math_win.out"
else
  set +e
  "$WINE" blue_bin.exe -compile examples/aot-math/main.js -o "$TMP_ROOT/blue_math_win.exe" \
    > "$TMP_ROOT/compile.stdout" 2> "$TMP_ROOT/compile.stderr"
  rc=$?
  set -e
  if [[ $rc -eq 0 ]]; then
    echo "expected compile to fail without a Windows g++ in the Wine prefix" >&2
    exit 1
  fi
  cat "$TMP_ROOT/compile.stdout" "$TMP_ROOT/compile.stderr" > "$TMP_ROOT/compile.combined"
  grep -q 'C++ compiler failed' "$TMP_ROOT/compile.combined"
  grep -q 'libblue_runtime_win\.a' "$TMP_ROOT/compile.combined"
  grep -q 'vendor/quickjs/obj-win' "$TMP_ROOT/compile.combined"
  echo "[skip] Wine prefix has no Windows g++; verified Windows artifact selection before compiler handoff."
fi

echo "=== pass ==="
